### ISSUE TITLE
preset-create-react-app: CRA build configuration affected where Storybook's generated CSS is placed

### ISSUE THREAD

**Issue by ignas-sedunovas** [storybookjs/presets#97] opened 2020-01-24 16:34 UTC
First, I want to thank for the effort put into documenting Storybook migration from `5.2.8` to `5.3.8`. Most of the things went smoothly. And I really like the simplifications you introduced 👏.

But I bumped into a small issue. I seems that the fonts are not longer loading.

My investigation showed that original CRA build configuration affected where Storybook's generated CSS is placed, but the paths in this generated CSS were not adjusted.

Storybook `5.2.8` (with _implicit_ CRA preset) used to create this structure:
![image](https://user-images.githubusercontent.com/3921290/73083998-74ad8200-3ecc-11ea-90c3-7d6b7d719975.png)
Everything was good here: main CSS was placed at the root of `/storybook` and fonts were loaded from a relative folder (combined path was `/storybook/static/media`)

Storybook `5.3.8` (with _explicit_ `preset-create-react-app@1.5.2` preset) mimics React build and creates the following structure where generated CSS is placed under `/storybook/static/css`
![image](https://user-images.githubusercontent.com/3921290/73083688-ea651e00-3ecb-11ea-90d2-40071af27a63.png)
(I used `build-storybook -o build/.infrastructure/storybook` to put Storybook's files into the same folder as React)

But the CSS generated with Storybook `5.3.8` still tries to load fonts relatively to the main CSS file location:
![image](https://user-images.githubusercontent.com/3921290/73083810-1ed8da00-3ecc-11ea-8ff3-8fa7ffa246ce.png)
This results in the browser trying to load fonts from `/storybook/static/css/static/media` (which does not exist).

FYI, when I run Storybook locally with `start-storybook`, I have no font loading issues.

I'm using these versions:
```
react-scripts 3.3.0
@storybook/react 5.3.8
@storybook/preset-create-react-app 1.5.2
```

Let me know if any additional information is necessary.

**Comment by mrmckeb** [comment] 2020-01-30 09:59
Hi @ignas-sedunovas, I think I understand the problem here. We're now fully using the CRA webpack config, instead of relying on a mix of CRA and Storybook - as this caused a lot of issues.

Are you able to provide a minimal repro repo? I can then take a look and resolve this one.

**Comment by ignas-sedunovas** [comment] 2020-01-30 19:12
Thanks for looking into this, @mrmckeb. Here's the repo: https://github.com/ignas-sedunovas/storybook-preset-create-react-app-issue.

**Some details that might be helpful:**
- I added CRA + TS and Storybook. Then I wrote a story. At this point fonts are rendering correctly both in local server and static file ([repo at this commit](https://github.com/ignas-sedunovas/storybook-preset-create-react-app-issue/tree/3a5e49f8cd342e8558d028be6500b338a313c1b6)) ✔
- Then I converted the story to TSX and added `@storybook/preset-create-react-app` addon. At this point Storybook complained about missing Webpack loaders. Therefore, I moved the story under `/src` folder. Now the Storybook successfully loads the story. Unfortunately, when I use the static build, the font is not loaded because of incorrect path (see image below) ❌

![image](https://user-images.githubusercontent.com/3921290/73480062-76c68380-4399-11ea-9bf1-b8fb07fbd41b.png)

**Comment by VojGin** [comment] 2020-02-04 16:12
The same happens to me for images linked from CSS files

![image](https://user-images.githubusercontent.com/5146396/73762760-da252c80-4770-11ea-9b3a-0b07e90def14.png)

<img width="637" alt="Bez názvu" src="https://user-images.githubusercontent.com/5146396/73763301-87984000-4771-11ea-9640-bde090394ba8.png">

**Comment by mrmckeb** [comment] 2020-02-11 09:05
Hi @ignas-sedunovas and @VojGin - I'm very sorry for the long time between replies. I was away on business.

I think this is likely caused by the CRA preset's implementation of file-loader, but I need to investigate more to understand why. The repo provided above will be very helpful @ignas-sedunovas.

It may be as simple as redefining the static path... 

I'll be able to look later this week - but if anyone can take a look beforehand, that would be greatly appreciated.

**Comment by functionalDev** [comment] 2020-03-10 16:58
this issue seems to be a dublication of https://github.com/storybookjs/storybook/issues/9564
I found a workaround by adjusting the config for the file-loader in main.js
```javascript
const getFileLoader = (config) => {
  const { oneOf } = config.module.rules.find(({oneOf}) => oneOf);
  return oneOf.find(({loader}) => /file-loader/.test(loader));
};
module.exports = {
  stories: ['../src/stories/*.stories.js'],
  addons: [
    '@storybook/preset-create-react-app',
  ],
  webpackFinal: async (config) => {
    const fileLoader = getFileLoader(config);
    fileLoader.options.name = '/' + fileLoader.options.name;
    return config;
  },
};
```

**Comment by zeorin** [comment] 2020-03-13 10:02
I'm also having this problem. In my case Storybook is not served on the root path, instead on `/components` behind Nginx. How might I fix this in a relative-url manner?
I tried `loader.options.name = '../../' + loader.options.name;`, which fixes the import path, but doesn't actually include the files in the output.

**Comment by mrmckeb** [comment] 2020-03-27 09:12
This should now be solved in the latest release. Can someone please test?

If using the preset, we strongly recommend you don't have any custom Webpack config.

**Comment by ocean90** [comment] 2020-03-27 10:49
@mrmckeb Thanks, confirmed that it's now working with 2.1.1.

**Comment by mrmckeb** [comment] 2020-03-31 07:17
Thank you! WIll close this off.

**Closed by mrmckeb** 2020-03-31 07:17 UTC
Labels: bug, create-react-app

**Comment by andrewmadridista** [comment] 2020-10-01 13:45
Hello. Issue is reproduced with the new versions:
    "@storybook/react": "6.0.22",
    "@storybook/preset-create-react-app": "3.1.4",
    "react-scripts": "3.4.3"
Adjusting the config for the file-loader in main.js still fixes the issue.
