### ISSUE TITLE
Basic CRA preset does not work on clean project

### ISSUE THREAD

**Issue by colingm** [storybookjs/presets#78] opened 2019-12-15 23:47 UTC
Hey I have tried setting up a new CRA project using CRA 3.3.0 and adding storybook (cli version 5.2.8) with the CRA preset and it immediately errors out. Below I am including the steps I took, the error message received, and a link to the git repo to reproduce the issue. Any help with what to do in this case would be great.

https://github.com/colingm/storybook-cra-error

```
npm i -g create-react-app@3.3.0 storybook@5.2.8
create-react-app sanity --template typescript
cd sanity
sb init
npm i @storybook/preset-create-react-app
echo "module.exports = ['@storybook/preset-create-react-app'];" > .storybook/presets.js
npm run storybook
```

```
ERROR in ./node_modules/is-map/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/cmaxfield/workspace/audit/sanity/node_modules/is-map/index.js: 'return' outside of function (12:1)

  10 | 		return false;
  11 | 	};
> 12 | 	return;
     | 	^
  13 | }
  14 |
  15 | var $mapHas = $Map ? Map.prototype.has : null;
    at Parser.raise (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:6983:17)
    at Parser.parseReturnStatement (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:11027:12)
    at Parser.parseStatementContent (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:10714:21)
    at Parser.parseStatement (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:10666:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:11242:25)
    at Parser.parseBlockBody (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:11229:10)
    at Parser.parseBlock (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:11213:10)
    at Parser.parseStatementContent (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:10742:21)
    at Parser.parseStatement (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:10666:17)
    at Parser.parseIfStatement (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:11020:28)
    at Parser.parseStatementContent (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:10711:21)
    at Parser.parseStatement (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:10666:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:11242:25)
    at Parser.parseBlockBody (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:11229:10)
    at Parser.parseTopLevel (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:10597:10)
    at Parser.parse (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:12107:10)
 @ ./node_modules/es-get-iterator/index.js 131:16-33
 @ ./node_modules/iterate-value/index.js
 @ ./node_modules/promise.allsettled/implementation.js
 @ ./node_modules/promise.allsettled/polyfill.js
 @ ./node_modules/promise.allsettled/shim.js
 @ ./node_modules/promise.allsettled/auto.js
 @ ./node_modules/airbnb-js-shims/target/es2020.js
 @ ./node_modules/airbnb-js-shims/target/es2019.js
 @ ./node_modules/airbnb-js-shims/target/es2018.js
 @ ./node_modules/airbnb-js-shims/target/es2017.js
 @ ./node_modules/airbnb-js-shims/target/es2016.js
 @ ./node_modules/airbnb-js-shims/target/es2015.js
 @ ./node_modules/airbnb-js-shims/target/es5.js
 @ ./node_modules/airbnb-js-shims/index.js
 @ ./node_modules/@storybook/core/dist/server/common/polyfills.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true&quiet=true

ERROR in ./node_modules/is-set/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/cmaxfield/workspace/audit/sanity/node_modules/is-set/index.js: 'return' outside of function (12:1)

  10 | 		return false;
  11 | 	};
> 12 | 	return;
     | 	^
  13 | }
  14 |
  15 | var $mapHas = $Map ? Map.prototype.has : null;
    at Parser.raise (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:6983:17)
    at Parser.parseReturnStatement (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:11027:12)
    at Parser.parseStatementContent (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:10714:21)
    at Parser.parseStatement (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:10666:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:11242:25)
    at Parser.parseBlockBody (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:11229:10)
    at Parser.parseBlock (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:11213:10)
    at Parser.parseStatementContent (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:10742:21)
    at Parser.parseStatement (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:10666:17)
    at Parser.parseIfStatement (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:11020:28)
    at Parser.parseStatementContent (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:10711:21)
    at Parser.parseStatement (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:10666:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:11242:25)
    at Parser.parseBlockBody (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:11229:10)
    at Parser.parseTopLevel (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:10597:10)
    at Parser.parse (/Users/cmaxfield/workspace/audit/sanity/node_modules/@babel/parser/lib/index.js:12107:10)
 @ ./node_modules/es-get-iterator/index.js 133:16-33
 @ ./node_modules/iterate-value/index.js
 @ ./node_modules/promise.allsettled/implementation.js
 @ ./node_modules/promise.allsettled/polyfill.js
 @ ./node_modules/promise.allsettled/shim.js
 @ ./node_modules/promise.allsettled/auto.js
 @ ./node_modules/airbnb-js-shims/target/es2020.js
 @ ./node_modules/airbnb-js-shims/target/es2019.js
 @ ./node_modules/airbnb-js-shims/target/es2018.js
 @ ./node_modules/airbnb-js-shims/target/es2017.js
 @ ./node_modules/airbnb-js-shims/target/es2016.js
 @ ./node_modules/airbnb-js-shims/target/es2015.js
 @ ./node_modules/airbnb-js-shims/target/es5.js
 @ ./node_modules/airbnb-js-shims/index.js
 @ ./node_modules/@storybook/core/dist/server/common/polyfills.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true&quiet=true
```

**Comment by shilman** [comment] 2019-12-16 03:27
What I did:

| setup | result |
| sb@5.2.8 | O |
| sb@5.2.8 + preset-cra@1.4 | X |
| sb@5.3.0-beta.25 | X |
| sb@5.3.0-beta.25 - preset-cra@1.4 | O |
| sb@5.3.0-beta.25 + preset-cra@* | X |

In other words, the problem appears to be an incompatibility between `@storybook/preset-create-react-app` and something else in the ecosystem (latest version of CRA? some change in `inspect-js` (see also: https://github.com/inspect-js/is-map/pull/3)?

**Comment by pocka** [comment] 2019-12-16 06:43
It seems that this rule tries to transpile is-map and fails?

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js#L455

**Comment by mrmckeb** [comment] 2019-12-16 08:36
I've found the issue here and will push it shortly.

**Comment by shilman** [comment] 2019-12-16 09:26
Fixed in `@storybook/preset-create-react-app@1.5.0`!! Please upgrade and try it out! Thanks @mrmckeb for the fix 🙌

**Closed by shilman** 2019-12-16 09:26 UTC
Labels: bug, create-react-app

**Comment by colingm** [comment] 2019-12-16 14:08
Upgrading takes care of it, thank you so much for the quick turn around everyone!

**Comment by n8sabes** [comment] 2019-12-17 03:42
@mrmckeb and @shilman -- What was the cause and solution of this issue? I am running into the same problem with another (more mature) CRA project. Downgrading `deep-equal to 1.1.1` works around the problem but unsure of the true origin or "correct" fix. Any insight is appreciated.

Please see:
[deep-equal issue #78](https://github.com/inspect-js/node-deep-equal/issues/78)

**Comment by ljharb** [comment] 2019-12-17 07:05
Top-level return is perfectly valid inside node modules; transpiling code you didn't author is unsafe; if you're going to transpile node_modules, then you should be sure to use settings that work on valid node modules :-)

**Comment by mrmckeb** [comment] 2019-12-17 19:50
@n8sabes, this was caused by the CRA preset applying the wrong loader to files imported by Storybook. 

The correction is here:
https://github.com/storybookjs/presets/pull/77/files#diff-80b3f28ef184f3c7a4ac83b1974c3dc6R147

Which ensures that an earlier loader (we use `oneOf`) catches the file, so that it isn't accidentally processed as application code.

**Comment by mrmckeb** [comment] 2019-12-17 19:56
@ljharb you're right - but this was never meant to be transpiled, it was simply omitted from the original preset - the new preset was forked from that, and the bug was carried over.

This is the related code:
https://github.com/SeedJobs/react-scripts/blob/master/packages/react-scripts/config/webpack.config.js#L489

**Comment by dbenfouzari** [comment] 2020-01-13 09:21
Hello guys !

I just get the exact same problem with newly generated project.
Steps :

* `npx create-react-app myproject --typescript`
* `npx -p @storybook/cli sb init --type react`
* `yarn add -D @storybook/preset-create-react-app`
* in ".storybook/main.js" > `addons: ['@storybook/addon-actions', '@storybook/addon-links'],`

But it results to : 
```
Module parse failed: Unexpected token (10:33)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| };
| 
> export const ToStorybook = () => <Welcome showApp={linkTo('Button')} />;
| 
| ToStorybook.story = {
Error: Module parse failed: Unexpected token (10:33)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| };
| 
> export const ToStorybook = () => <Welcome showApp={linkTo('Button')} />;
| 
| ToStorybook.story = {
    at Object../stories/0-Welcome.stories.js (http://localhost:6006/main.bfbb4c2484bd25f72ff3.bundle.js:62:7)
    at __webpack_require__ (http://localhost:6006/runtime~main.bfbb4c2484bd25f72ff3.bundle.js:786:30)
    at fn (http://localhost:6006/runtime~main.bfbb4c2484bd25f72ff3.bundle.js:151:20)
    at webpackContext (http://localhost:6006/main.bfbb4c2484bd25f72ff3.bundle.js:36:9)
    at http://localhost:6006/vendors~main.bfbb4c2484bd25f72ff3.bundle.js:3849:31
    at Array.forEach (<anonymous>)
    at http://localhost:6006/vendors~main.bfbb4c2484bd25f72ff3.bundle.js:3848:22
    at Array.forEach (<anonymous>)
    at http://localhost:6006/vendors~main.bfbb4c2484bd25f72ff3.bundle.js:3847:14
    at render (http://localhost:6006/vendors~main.bfbb4c2484bd25f72ff3.bundle.js:1897:13)
```
